# Generated by Django 5.2.5 on 2025-08-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='no_of_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='seats_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
