# Generated by Django 5.2.5 on 2025-09-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Bookings', '0002_alter_bookingdetails_no_of_tickets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(unique=True)),
                ('descp', models.TextField(blank=True, null=True)),
                ('tickets_avail', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('location', models.TextField()),
                ('venue', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_category', models.TextField(choices=[('Concert', 'Concert'), ('Workshop', 'Workshop'), ('Reunion', 'Reunion'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Fashion Show', 'Fashion Show'), ('Conference', 'Conference'), ('Graduation', 'Graduation'), ('Private Party', 'Private Party'), ('Other', 'Other'), ('Corporate Event', 'Corporate Event'), ('Exhibition', 'Exhibition'), ('Festival', 'Festival'), ('Meetup', 'Meetup'), ('Sports Event', 'Sports Event'), ('Cultural Event', 'Cultural Event'), ('Film Screening', 'Film Screening'), ('Birthday', 'Birthday'), ('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Charity Event', 'Charity Event')])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='Accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventAdd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='Bookings.eventadd')),
            ],
        ),
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.eventadd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventBook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
