# Generated by Django 5.2.5 on 2025-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_eventadd_budget_eventbook_delete_bookingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadd',
            name='role',
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Seminar', 'Seminar'), ('Sports Event', 'Sports Event'), ('Meetup', 'Meetup'), ('Corporate Event', 'Corporate Event'), ('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Birthday', 'Birthday'), ('Exhibition', 'Exhibition'), ('Workshop', 'Workshop'), ('Other', 'Other'), ('Private Party', 'Private Party'), ('Reunion', 'Reunion'), ('Webinar', 'Webinar'), ('Charity Event', 'Charity Event'), ('Concert', 'Concert'), ('Film Screening', 'Film Screening'), ('Fashion Show', 'Fashion Show'), ('Graduation', 'Graduation'), ('Cultural Event', 'Cultural Event'), ('Festival', 'Festival'), ('Anniversary', 'Anniversary')]),
        ),
    ]
