# Generated by Django 5.2.5 on 2025-09-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_remove_eventadd_role_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Charity Event', 'Charity Event'), ('Private Party', 'Private Party'), ('Birthday', 'Birthday'), ('Fashion Show', 'Fashion Show'), ('Graduation', 'Graduation'), ('Reunion', 'Reunion'), ('Cultural Event', 'Cultural Event'), ('Sports Event', 'Sports Event'), ('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Webinar', 'Webinar'), ('Exhibition', 'Exhibition'), ('Meetup', 'Meetup'), ('Concert', 'Concert'), ('Seminar', 'Seminar'), ('Anniversary', 'Anniversary'), ('Corporate Event', 'Corporate Event'), ('Festival', 'Festival'), ('Other', 'Other'), ('Film Screening', 'Film Screening'), ('Workshop', 'Workshop')]),
        ),
    ]
