# Generated by Django 5.2.5 on 2025-09-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Wedding', 'Wedding'), ('Exhibition', 'Exhibition'), ('Concert', 'Concert'), ('Festival', 'Festival'), ('Reunion', 'Reunion'), ('Anniversary', 'Anniversary'), ('Private Party', 'Private Party'), ('Webinar', 'Webinar'), ('Birthday', 'Birthday'), ('Workshop', 'Workshop'), ('Cultural Event', 'Cultural Event'), ('Conference', 'Conference'), ('Sports Event', 'Sports Event'), ('Meetup', 'Meetup'), ('Seminar', 'Seminar'), ('Graduation', 'Graduation'), ('Charity Event', 'Charity Event'), ('Other', 'Other'), ('Fashion Show', 'Fashion Show'), ('Corporate Event', 'Corporate Event'), ('Film Screening', 'Film Screening')]),
        ),
    ]
