# Generated by Django 5.2.5 on 2025-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Film Screening', 'Film Screening'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Private Party', 'Private Party'), ('Reunion', 'Reunion'), ('Fashion Show', 'Fashion Show'), ('Cultural Event', 'Cultural Event'), ('Charity Event', 'Charity Event'), ('Graduation', 'Graduation'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Festival', 'Festival'), ('Meetup', 'Meetup'), ('Seminar', 'Seminar'), ('Other', 'Other'), ('Corporate Event', 'Corporate Event'), ('Sports Event', 'Sports Event'), ('Concert', 'Concert'), ('Exhibition', 'Exhibition'), ('Wedding', 'Wedding'), ('Webinar', 'Webinar')]),
        ),
    ]
