# Generated by Django 5.2.5 on 2025-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadd',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Private Party', 'Private Party'), ('Film Screening', 'Film Screening'), ('Corporate Event', 'Corporate Event'), ('Webinar', 'Webinar'), ('Wedding', 'Wedding'), ('Anniversary', 'Anniversary'), ('Festival', 'Festival'), ('Charity Event', 'Charity Event'), ('Reunion', 'Reunion'), ('Fashion Show', 'Fashion Show'), ('Graduation', 'Graduation'), ('Conference', 'Conference'), ('Cultural Event', 'Cultural Event'), ('Concert', 'Concert'), ('Exhibition', 'Exhibition'), ('Seminar', 'Seminar'), ('Birthday', 'Birthday'), ('Meetup', 'Meetup'), ('Sports Event', 'Sports Event'), ('Workshop', 'Workshop'), ('Other', 'Other')]),
        ),
    ]
