# Generated by Django 5.2.5 on 2025-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_eventadd_total_tickets_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Anniversary', 'Anniversary'), ('Exhibition', 'Exhibition'), ('Cultural Event', 'Cultural Event'), ('Festival', 'Festival'), ('Sports Event', 'Sports Event'), ('Charity Event', 'Charity Event'), ('Other', 'Other'), ('Private Party', 'Private Party'), ('Corporate Event', 'Corporate Event'), ('Workshop', 'Workshop'), ('Film Screening', 'Film Screening'), ('Conference', 'Conference'), ('Graduation', 'Graduation'), ('Concert', 'Concert'), ('Seminar', 'Seminar'), ('Reunion', 'Reunion'), ('Fashion Show', 'Fashion Show'), ('Webinar', 'Webinar'), ('Meetup', 'Meetup'), ('Birthday', 'Birthday'), ('Wedding', 'Wedding')]),
        ),
    ]
