# Generated by Django 5.2.5 on 2025-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_eventbook_tickets_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Cultural Event', 'Cultural Event'), ('Sports Event', 'Sports Event'), ('Private Party', 'Private Party'), ('Reunion', 'Reunion'), ('Wedding', 'Wedding'), ('Charity Event', 'Charity Event'), ('Webinar', 'Webinar'), ('Fashion Show', 'Fashion Show'), ('Concert', 'Concert'), ('Workshop', 'Workshop'), ('Anniversary', 'Anniversary'), ('Conference', 'Conference'), ('Corporate Event', 'Corporate Event'), ('Film Screening', 'Film Screening'), ('Festival', 'Festival'), ('Birthday', 'Birthday'), ('Meetup', 'Meetup'), ('Seminar', 'Seminar'), ('Other', 'Other'), ('Exhibition', 'Exhibition'), ('Graduation', 'Graduation')]),
        ),
        migrations.AlterField(
            model_name='eventbook',
            name='tickets',
            field=models.IntegerField(),
        ),
    ]
