# Generated by Django 5.2.5 on 2025-09-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_alter_eventadd_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Other', 'Other'), ('Concert', 'Concert'), ('Cultural Event', 'Cultural Event'), ('Exhibition', 'Exhibition'), ('Charity Event', 'Charity Event'), ('Conference', 'Conference'), ('Meetup', 'Meetup'), ('Graduation', 'Graduation'), ('Private Party', 'Private Party'), ('Sports Event', 'Sports Event'), ('Birthday', 'Birthday'), ('Webinar', 'Webinar'), ('Anniversary', 'Anniversary'), ('Workshop', 'Workshop'), ('Film Screening', 'Film Screening'), ('Seminar', 'Seminar'), ('Wedding', 'Wedding'), ('Corporate Event', 'Corporate Event'), ('Reunion', 'Reunion'), ('Fashion Show', 'Fashion Show'), ('Festival', 'Festival')]),
        ),
    ]
