# Generated by Django 5.2.5 on 2025-09-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_eventbook_amount_alter_eventadd_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Corporate Event', 'Corporate Event'), ('Fashion Show', 'Fashion Show'), ('Concert', 'Concert'), ('Meetup', 'Meetup'), ('Film Screening', 'Film Screening'), ('Anniversary', 'Anniversary'), ('Private Party', 'Private Party'), ('Cultural Event', 'Cultural Event'), ('Webinar', 'Webinar'), ('Sports Event', 'Sports Event'), ('Other', 'Other'), ('Birthday', 'Birthday'), ('Seminar', 'Seminar'), ('Charity Event', 'Charity Event'), ('Festival', 'Festival'), ('Workshop', 'Workshop'), ('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Graduation', 'Graduation'), ('Reunion', 'Reunion'), ('Exhibition', 'Exhibition')]),
        ),
        migrations.AlterField(
            model_name='eventbook',
            name='amount',
            field=models.FloatField(),
        ),
    ]
