# Generated by Django 5.2.5 on 2025-09-07 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_alter_eventadd_event_category_alter_eventbook_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadd',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventadd',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventadd',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='eventadd',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='eventadd',
            name='terms',
        ),
        migrations.AddField(
            model_name='eventbook',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbook',
            name='terms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Exhibition', 'Exhibition'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('Sports Event', 'Sports Event'), ('Fashion Show', 'Fashion Show'), ('Cultural Event', 'Cultural Event'), ('Seminar', 'Seminar'), ('Meetup', 'Meetup'), ('Reunion', 'Reunion'), ('Graduation', 'Graduation'), ('Webinar', 'Webinar'), ('Charity Event', 'Charity Event'), ('Other', 'Other'), ('Film Screening', 'Film Screening'), ('Anniversary', 'Anniversary'), ('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Private Party', 'Private Party'), ('Festival', 'Festival'), ('Concert', 'Concert'), ('Corporate Event', 'Corporate Event')]),
        ),
    ]
