# Generated by Django 5.2.5 on 2025-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0013_remove_eventadd_end_date_remove_eventadd_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadd',
            name='end_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventadd',
            name='start_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Webinar', 'Webinar'), ('Seminar', 'Seminar'), ('Corporate Event', 'Corporate Event'), ('Film Screening', 'Film Screening'), ('Cultural Event', 'Cultural Event'), ('Graduation', 'Graduation'), ('Exhibition', 'Exhibition'), ('Meetup', 'Meetup'), ('Wedding', 'Wedding'), ('Other', 'Other'), ('Concert', 'Concert'), ('Reunion', 'Reunion'), ('Conference', 'Conference'), ('Fashion Show', 'Fashion Show'), ('Sports Event', 'Sports Event'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Private Party', 'Private Party'), ('Charity Event', 'Charity Event'), ('Workshop', 'Workshop'), ('Festival', 'Festival')]),
        ),
    ]
