# Generated by Django 5.2.5 on 2025-09-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0014_eventadd_end_at_eventadd_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Webinar', 'Webinar'), ('Charity Event', 'Charity Event'), ('Conference', 'Conference'), ('Cultural Event', 'Cultural Event'), ('Private Party', 'Private Party'), ('Festival', 'Festival'), ('Workshop', 'Workshop'), ('Birthday', 'Birthday'), ('Sports Event', 'Sports Event'), ('Wedding', 'Wedding'), ('Concert', 'Concert'), ('Reunion', 'Reunion'), ('Exhibition', 'Exhibition'), ('Film Screening', 'Film Screening'), ('Other', 'Other'), ('Corporate Event', 'Corporate Event'), ('Meetup', 'Meetup'), ('Seminar', 'Seminar'), ('Fashion Show', 'Fashion Show'), ('Anniversary', 'Anniversary'), ('Graduation', 'Graduation')]),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
