# Generated by Django 5.2.5 on 2025-09-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0015_alter_eventadd_end_at_alter_eventadd_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Corporate Event', 'Corporate Event'), ('Workshop', 'Workshop'), ('Film Screening', 'Film Screening'), ('Anniversary', 'Anniversary'), ('Cultural Event', 'Cultural Event'), ('Concert', 'Concert'), ('Private Party', 'Private Party'), ('Reunion', 'Reunion'), ('Charity Event', 'Charity Event'), ('Meetup', 'Meetup'), ('Wedding', 'Wedding'), ('Festival', 'Festival'), ('Other', 'Other'), ('Birthday', 'Birthday'), ('Exhibition', 'Exhibition'), ('Graduation', 'Graduation'), ('Sports Event', 'Sports Event'), ('Conference', 'Conference'), ('Webinar', 'Webinar'), ('Seminar', 'Seminar'), ('Fashion Show', 'Fashion Show')]),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='event_name',
            field=models.TextField(),
        ),
    ]
