# Generated by Django 5.2.5 on 2025-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0016_alter_eventadd_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_category',
            field=models.TextField(choices=[('Graduation', 'Graduation'), ('Wedding', 'Wedding'), ('Festival', 'Festival'), ('Anniversary', 'Anniversary'), ('Webinar', 'Webinar'), ('Cultural Event', 'Cultural Event'), ('Reunion', 'Reunion'), ('Exhibition', 'Exhibition'), ('Sports Event', 'Sports Event'), ('Conference', 'Conference'), ('Concert', 'Concert'), ('Fashion Show', 'Fashion Show'), ('Corporate Event', 'Corporate Event'), ('Private Party', 'Private Party'), ('Birthday', 'Birthday'), ('Film Screening', 'Film Screening'), ('Seminar', 'Seminar'), ('Other', 'Other'), ('Workshop', 'Workshop'), ('Charity Event', 'Charity Event'), ('Meetup', 'Meetup')]),
        ),
    ]
